// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  header_section: dynamic(() => import("./HeaderSection")),
  testimonial_section: dynamic(() => import("./TestimonialSection")),
};
