// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *FloatWpp → whatsapp*
 */
export interface FloatwppDocumentDataWhatsappItem {
  /**
   * link field in *FloatWpp → whatsapp*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: floatwpp.whatsapp[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * icon field in *FloatWpp → whatsapp*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: floatwpp.whatsapp[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<"1" | "0", "filled">;
}

/**
 * Content for FloatWpp documents
 */
interface FloatwppDocumentData {
  /**
   * whatsapp field in *FloatWpp*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: floatwpp.whatsapp[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  whatsapp: prismic.GroupField<Simplify<FloatwppDocumentDataWhatsappItem>>;
}

/**
 * FloatWpp document from Prismic
 *
 * - **API ID**: `floatwpp`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FloatwppDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FloatwppDocumentData>,
    "floatwpp",
    Lang
  >;

/**
 * Item in *footer → social*
 */
export interface FooterDocumentDataSocialItem {
  /**
   * label field in *footer → social*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *footer → social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon field in *footer → social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: footer.social[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<"1" | "2" | "3" | "4", "filled">;
}

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * social field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social: prismic.GroupField<Simplify<FooterDocumentDataSocialItem>>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *home → navigation*
 */
export interface HomeDocumentDataNavigationItem {
  /**
   * link field in *home → navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * label field in *home → navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

type HomeDocumentDataSlicesSlice =
  | HeaderSectionSlice
  | StackSectionSlice
  | ServiceSectionSlice
  | ProjectSectionSlice
  | ContactSectionSlice
  | AboutSectionSlice
  | CtaFooterSlice
  | TestimonialsSlice
  | HeroSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * tslogo field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.tslogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  tslogo: prismic.ImageField<never>;

  /**
   * navigation field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<HomeDocumentDataNavigationItem>>;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *NavBar → navigation*
 */
export interface NavbarDocumentDataNavigationItem {
  /**
   * label field in *NavBar → navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *NavBar → navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for NavBar documents
 */
interface NavbarDocumentData {
  /**
   * navigation field in *NavBar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<NavbarDocumentDataNavigationItem>>;
}

/**
 * NavBar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

export type AllDocumentTypes =
  | FloatwppDocument
  | FooterDocument
  | HomeDocument
  | NavbarDocument;

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Company Image field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.company_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  company_image: prismic.ImageField<never>;

  /**
   * Company Name field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.company_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_name: prismic.KeyTextField;

  /**
   * Paragraph Text Card Title field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.paragraph_text_card_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph_text_card_title: prismic.RichTextField;

  /**
   * Paragraph Text Card Subtitle field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.paragraph_text_card_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph_text_card_subtitle: prismic.RichTextField;

  /**
   * Text field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Primary content in *ContactSection → Default → Primary*
 */
export interface ContactSectionSliceDefaultPrimary {
  /**
   * Título field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Fale Connosco
   * - **API ID Path**: contact_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto Descritivo field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * E-mail da Empresa field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Telefone / WhatsApp field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: Secção de Contato
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Item in *CtaFooter → Default → Primary → socials*
 */
export interface CtaFooterSliceDefaultPrimarySocialsItem {
  /**
   * image field in *CtaFooter → Default → Primary → socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.socials[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * socials link field in *CtaFooter → Default → Primary → socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.socials[].socials_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  socials_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *CtaFooter → Default → Primary*
 */
export interface CtaFooterSliceDefaultPrimary {
  /**
   * title field in *CtaFooter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * sub field in *CtaFooter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.sub
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub: prismic.RichTextField;

  /**
   * socials field in *CtaFooter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.socials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socials: prismic.GroupField<
    Simplify<CtaFooterSliceDefaultPrimarySocialsItem>
  >;
}

/**
 * Default variation for CtaFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaFooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaFooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaFooter*
 */
type CtaFooterSliceVariation = CtaFooterSliceDefault;

/**
 * CtaFooter Shared Slice
 *
 * - **API ID**: `cta_footer`
 * - **Description**: CtaFooter
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaFooterSlice = prismic.SharedSlice<
  "cta_footer",
  CtaFooterSliceVariation
>;

/**
 * Primary content in *HeaderSection → Default → Primary*
 */
export interface HeaderSectionSliceDefaultPrimary {
  /**
   * Company Name field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.company_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_name: prismic.KeyTextField;

  /**
   * Sub_title field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_title: prismic.RichTextField;

  /**
   * Button Text 1 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.button_text_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text_1: prismic.KeyTextField;

  /**
   * Button Link 1 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.button_link_1
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link_1: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text 2 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.button_text_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text_2: prismic.KeyTextField;

  /**
   * Button Link 2 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.button_link_2
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link_2: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image 1 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.image_3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Text Card Title field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.text_card_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_card_title: prismic.RichTextField;

  /**
   * Text Card Subtitle field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.text_card_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_card_subtitle: prismic.RichTextField;
}

/**
 * Primary content in *HeaderSection → Items*
 */
export interface HeaderSectionSliceDefaultItem {
  /**
   * Topics field in *HeaderSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.items[].topics
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  topics: prismic.KeyTextField;
}

/**
 * Default variation for HeaderSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSectionSliceDefaultPrimary>,
  Simplify<HeaderSectionSliceDefaultItem>
>;

/**
 * Slice variation for *HeaderSection*
 */
type HeaderSectionSliceVariation = HeaderSectionSliceDefault;

/**
 * HeaderSection Shared Slice
 *
 * - **API ID**: `header_section`
 * - **Description**: HeaderSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSectionSlice = prismic.SharedSlice<
  "header_section",
  HeaderSectionSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Topicos Hero*
 */
export interface HeroSliceDefaultPrimaryTopicosHeroItem {
  /**
   * Texto field in *Hero → Default → Primary → Topicos Hero*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.topicos_hero[].texto
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texto: prismic.RichTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Nome da Empresa field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Adicione o nome da empresa
   * - **API ID Path**: hero.default.primary.nome_da_empresa
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  nome_da_empresa: prismic.RichTextField;

  /**
   * Hero Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Adicione o Título do seu Hero
   * - **API ID Path**: hero.default.primary.hero_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_text: prismic.RichTextField;

  /**
   * Topicos Hero field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.topicos_hero[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  topicos_hero: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryTopicosHeroItem>
  >;

  /**
   * Button Contate field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Botão para contato
   * - **API ID Path**: hero.default.primary.button_contate
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_contate: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button SaibaMais field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_saibamais
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_saibamais: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ProjectSection → Default → Primary*
 */
export interface ProjectSectionSliceDefaultPrimary {
  /**
   * Título da Secção field in *ProjectSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Alguns Projetos Realizados
   * - **API ID Path**: project_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ProjectSection → Items*
 */
export interface ProjectSectionSliceDefaultItem {
  /**
   * Imagem do Projeto field in *ProjectSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_section.items[].project_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  project_image: prismic.ImageField<never>;

  /**
   * Título do Projeto field in *ProjectSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: GuiaServ
   * - **API ID Path**: project_section.items[].project_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_title: prismic.KeyTextField;

  /**
   * Descrição do Projeto field in *ProjectSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Fale um pouco sobre o projeto
   * - **API ID Path**: project_section.items[].project_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;
}

/**
 * Default variation for ProjectSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSectionSliceDefaultPrimary>,
  Simplify<ProjectSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ProjectSection*
 */
type ProjectSectionSliceVariation = ProjectSectionSliceDefault;

/**
 * ProjectSection Shared Slice
 *
 * - **API ID**: `project_section`
 * - **Description**: Portfólio de Projetos
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSectionSlice = prismic.SharedSlice<
  "project_section",
  ProjectSectionSliceVariation
>;

/**
 * Primary content in *ServiceSection → Default → Primary*
 */
export interface ServiceSectionSliceDefaultPrimary {
  /**
   * Título da Secção field in *ServiceSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Nossos Serviços
   * - **API ID Path**: service_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ServiceSection → Items*
 */
export interface ServiceSectionSliceDefaultItem {
  /**
   * Nome do Serviço field in *ServiceSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: Desenvolvimento Web
   * - **API ID Path**: service_section.items[].service_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_name: prismic.KeyTextField;

  /**
   * Descrição do Serviço field in *ServiceSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Breve descrição do que consiste o serviço
   * - **API ID Path**: service_section.items[].service_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  service_description: prismic.RichTextField;
}

/**
 * Default variation for ServiceSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceSectionSliceDefaultPrimary>,
  Simplify<ServiceSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ServiceSection*
 */
type ServiceSectionSliceVariation = ServiceSectionSliceDefault;

/**
 * ServiceSection Shared Slice
 *
 * - **API ID**: `service_section`
 * - **Description**: Secção de Serviços oferecidos
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceSectionSlice = prismic.SharedSlice<
  "service_section",
  ServiceSectionSliceVariation
>;

/**
 * Primary content in *StackSection → Default → Primary*
 */
export interface StackSectionSliceDefaultPrimary {
  /**
   * Título da Secção field in *StackSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Nossas Tecnologias
   * - **API ID Path**: stack_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *StackSection → Items*
 */
export interface StackSectionSliceDefaultItem {
  /**
   * Nome da Tecnologia field in *StackSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: React, Node.js, Figma...
   * - **API ID Path**: stack_section.items[].tech_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tech_name: prismic.KeyTextField;

  /**
   * Logótipo da Tecnologia field in *StackSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stack_section.items[].tech_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  tech_image: prismic.ImageField<never>;
}

/**
 * Default variation for StackSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StackSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StackSectionSliceDefaultPrimary>,
  Simplify<StackSectionSliceDefaultItem>
>;

/**
 * Slice variation for *StackSection*
 */
type StackSectionSliceVariation = StackSectionSliceDefault;

/**
 * StackSection Shared Slice
 *
 * - **API ID**: `stack_section`
 * - **Description**: Secção de Tecnologias (Stack)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StackSectionSlice = prismic.SharedSlice<
  "stack_section",
  StackSectionSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → testimonial*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialItem {
  /**
   * Testimonial text field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].testimonial_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial_text: prismic.RichTextField;

  /**
   * Testimonial img field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].testimonial_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  testimonial_img: prismic.ImageField<never>;

  /**
   * testimonial user field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].testimonial_user
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial_user: prismic.RichTextField;

  /**
   * testimonial empresa field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].testimonial_empresa
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial_empresa: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Testimonials Titulo field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials_titulo
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonials_titulo: prismic.RichTextField;

  /**
   * Testimonials Subtitulo field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials_subtitulo
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonials_subtitulo: prismic.RichTextField;

  /**
   * Testimonials CTA field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials_cta
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonials_cta: prismic.RichTextField;

  /**
   * testimonial field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonial: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FloatwppDocument,
      FloatwppDocumentData,
      FloatwppDocumentDataWhatsappItem,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataNavigationItem,
      HomeDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataNavigationItem,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      CtaFooterSlice,
      CtaFooterSliceDefaultPrimarySocialsItem,
      CtaFooterSliceDefaultPrimary,
      CtaFooterSliceVariation,
      CtaFooterSliceDefault,
      HeaderSectionSlice,
      HeaderSectionSliceDefaultPrimary,
      HeaderSectionSliceDefaultItem,
      HeaderSectionSliceVariation,
      HeaderSectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryTopicosHeroItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProjectSectionSlice,
      ProjectSectionSliceDefaultPrimary,
      ProjectSectionSliceDefaultItem,
      ProjectSectionSliceVariation,
      ProjectSectionSliceDefault,
      ServiceSectionSlice,
      ServiceSectionSliceDefaultPrimary,
      ServiceSectionSliceDefaultItem,
      ServiceSectionSliceVariation,
      ServiceSectionSliceDefault,
      StackSectionSlice,
      StackSectionSliceDefaultPrimary,
      StackSectionSliceDefaultItem,
      StackSectionSliceVariation,
      StackSectionSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
