// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *FloatWpp → whatsapp*
 */
export interface FloatwppDocumentDataWhatsappItem {
  /**
   * link field in *FloatWpp → whatsapp*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: floatwpp.whatsapp[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * icon field in *FloatWpp → whatsapp*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: floatwpp.whatsapp[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<"1" | "0", "filled">;
}

/**
 * Content for FloatWpp documents
 */
interface FloatwppDocumentData {
  /**
   * whatsapp field in *FloatWpp*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: floatwpp.whatsapp[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  whatsapp: prismic.GroupField<Simplify<FloatwppDocumentDataWhatsappItem>>;
}

/**
 * FloatWpp document from Prismic
 *
 * - **API ID**: `floatwpp`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FloatwppDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FloatwppDocumentData>,
    "floatwpp",
    Lang
  >;

/**
 * Item in *footer → social*
 */
export interface FooterDocumentDataSocialItem {
  /**
   * label field in *footer → social*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *footer → social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon field in *footer → social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: footer.social[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<"1" | "2" | "3" | "4", "filled">;
}

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * social field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social: prismic.GroupField<Simplify<FooterDocumentDataSocialItem>>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | ContactSectionSlice
  | ProjectSectionSlice
  | ServiceSectionSlice
  | HeaderSectionSlice
  | TestimonialSectionSlice
  | AboutSectionSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *NavBar → navigation*
 */
export interface NavbarDocumentDataNavigationItem {
  /**
   * label field in *NavBar → navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *NavBar → navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for NavBar documents
 */
interface NavbarDocumentData {
  /**
   * navigation field in *NavBar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<NavbarDocumentDataNavigationItem>>;
}

/**
 * NavBar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

export type AllDocumentTypes =
  | FloatwppDocument
  | FooterDocument
  | HomeDocument
  | NavbarDocument;

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Company Image field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.company_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  company_image: prismic.ImageField<never>;

  /**
   * Company Name field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.company_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_name: prismic.KeyTextField;

  /**
   * Text field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Text Card Title field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.text_card_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_card_title: prismic.RichTextField;

  /**
   * Text Card Subtitle field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.text_card_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_card_subtitle: prismic.RichTextField;

  /**
   * Paragraph Text Card Title field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.paragraph_text_card_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph_text_card_title: prismic.RichTextField;

  /**
   * Paragraph Text Card Subtitle field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.paragraph_text_card_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph_text_card_subtitle: prismic.RichTextField;
}

/**
 * Primary content in *AboutSection → Items*
 */
export interface AboutSectionSliceDefaultItem {
  /**
   * Image field in *AboutSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *AboutSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *AboutSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  Simplify<AboutSectionSliceDefaultItem>
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: ContactSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Primary content in *HeaderSection → Default → Primary*
 */
export interface HeaderSectionSliceDefaultPrimary {
  /**
   * Company Name field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.company_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_name: prismic.KeyTextField;

  /**
   * Sub_title field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_title: prismic.RichTextField;

  /**
   * Button Text 1 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.button_text_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text_1: prismic.KeyTextField;

  /**
   * Button Link 1 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.button_link_1
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link_1: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text 2 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.button_text_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text_2: prismic.KeyTextField;

  /**
   * Button Link 2 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.button_link_2
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link_2: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image 1 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.image_3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Text Card Title field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.text_card_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_card_title: prismic.RichTextField;

  /**
   * Text Card Subtitle field in *HeaderSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.default.primary.text_card_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_card_subtitle: prismic.RichTextField;
}

/**
 * Primary content in *HeaderSection → Items*
 */
export interface HeaderSectionSliceDefaultItem {
  /**
   * Topics field in *HeaderSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.items[].topics
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  topics: prismic.KeyTextField;
}

/**
 * Default variation for HeaderSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSectionSliceDefaultPrimary>,
  Simplify<HeaderSectionSliceDefaultItem>
>;

/**
 * Slice variation for *HeaderSection*
 */
type HeaderSectionSliceVariation = HeaderSectionSliceDefault;

/**
 * HeaderSection Shared Slice
 *
 * - **API ID**: `header_section`
 * - **Description**: HeaderSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSectionSlice = prismic.SharedSlice<
  "header_section",
  HeaderSectionSliceVariation
>;

/**
 * Default variation for ProjectSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ProjectSection*
 */
type ProjectSectionSliceVariation = ProjectSectionSliceDefault;

/**
 * ProjectSection Shared Slice
 *
 * - **API ID**: `project_section`
 * - **Description**: ProjectSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSectionSlice = prismic.SharedSlice<
  "project_section",
  ProjectSectionSliceVariation
>;

/**
 * Default variation for ProjectSectios Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSectiosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ProjectSectios*
 */
type ProjectSectiosSliceVariation = ProjectSectiosSliceDefault;

/**
 * ProjectSectios Shared Slice
 *
 * - **API ID**: `project_sectios`
 * - **Description**: ProjectSectios
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSectiosSlice = prismic.SharedSlice<
  "project_sectios",
  ProjectSectiosSliceVariation
>;

/**
 * Default variation for ServiceSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ServiceSection*
 */
type ServiceSectionSliceVariation = ServiceSectionSliceDefault;

/**
 * ServiceSection Shared Slice
 *
 * - **API ID**: `service_section`
 * - **Description**: ServiceSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceSectionSlice = prismic.SharedSlice<
  "service_section",
  ServiceSectionSliceVariation
>;

/**
 * Primary content in *TestimonialSection → Default → Primary*
 */
export interface TestimonialSectionSliceDefaultPrimary {
  /**
   * Text Card Title field in *TestimonialSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.text_card_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_card_title: prismic.RichTextField;

  /**
   * Text Card Subtitle field in *TestimonialSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.text_card_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_card_subtitle: prismic.RichTextField;
}

/**
 * Primary content in *TestimonialSection → Items*
 */
export interface TestimonialSectionSliceDefaultItem {
  /**
   * Image field in *TestimonialSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *TestimonialSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *TestimonialSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Score field in *TestimonialSection → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].score
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  score: prismic.NumberField;
}

/**
 * Default variation for TestimonialSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSectionSliceDefaultPrimary>,
  Simplify<TestimonialSectionSliceDefaultItem>
>;

/**
 * Slice variation for *TestimonialSection*
 */
type TestimonialSectionSliceVariation = TestimonialSectionSliceDefault;

/**
 * TestimonialSection Shared Slice
 *
 * - **API ID**: `testimonial_section`
 * - **Description**: TestimonialSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSectionSlice = prismic.SharedSlice<
  "testimonial_section",
  TestimonialSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FloatwppDocument,
      FloatwppDocumentData,
      FloatwppDocumentDataWhatsappItem,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataNavigationItem,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceDefaultItem,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      HeaderSectionSlice,
      HeaderSectionSliceDefaultPrimary,
      HeaderSectionSliceDefaultItem,
      HeaderSectionSliceVariation,
      HeaderSectionSliceDefault,
      ProjectSectionSlice,
      ProjectSectionSliceVariation,
      ProjectSectionSliceDefault,
      ProjectSectiosSlice,
      ProjectSectiosSliceVariation,
      ProjectSectiosSliceDefault,
      ServiceSectionSlice,
      ServiceSectionSliceVariation,
      ServiceSectionSliceDefault,
      TestimonialSectionSlice,
      TestimonialSectionSliceDefaultPrimary,
      TestimonialSectionSliceDefaultItem,
      TestimonialSectionSliceVariation,
      TestimonialSectionSliceDefault,
    };
  }
}
