// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *FloatWpp → whatsapp*
 */
export interface FloatwppDocumentDataWhatsappItem {
  /**
   * link field in *FloatWpp → whatsapp*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: floatwpp.whatsapp[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * icon field in *FloatWpp → whatsapp*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: floatwpp.whatsapp[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"1" | "0", "filled">;
}

/**
 * Content for FloatWpp documents
 */
interface FloatwppDocumentData {
  /**
   * whatsapp field in *FloatWpp*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: floatwpp.whatsapp[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  whatsapp: prismic.GroupField<Simplify<FloatwppDocumentDataWhatsappItem>>;
}

/**
 * FloatWpp document from Prismic
 *
 * - **API ID**: `floatwpp`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FloatwppDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FloatwppDocumentData>,
    "floatwpp",
    Lang
  >;

/**
 * Item in *footer → social*
 */
export interface FooterDocumentDataSocialItem {
  /**
   * label field in *footer → social*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *footer → social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Icon field in *footer → social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: footer.social[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"1" | "2" | "3" | "4", "filled">;
}

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * social field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social: prismic.GroupField<Simplify<FooterDocumentDataSocialItem>>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | HeaderSectionSlice
  | TestimonialSectionSlice
  | AboutSectionSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *NavBar → navigation*
 */
export interface NavbarDocumentDataNavigationItem {
  /**
   * label field in *NavBar → navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *NavBar → navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for NavBar documents
 */
interface NavbarDocumentData {
  /**
   * navigation field in *NavBar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<NavbarDocumentDataNavigationItem>>;
}

/**
 * NavBar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

export type AllDocumentTypes =
  | FloatwppDocument
  | FooterDocument
  | HomeDocument
  | NavbarDocument;

/**
 * Primary content in *AboutSection → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Company Image field in *AboutSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.company_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_image: prismic.ImageField<never>;

  /**
   * Company Name field in *AboutSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.company_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Text field in *AboutSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Text Card Title field in *AboutSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.text_card_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_card_title: prismic.TitleField;

  /**
   * Text Card Subtitle field in *AboutSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.text_card_subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_card_subtitle: prismic.RichTextField;

  /**
   * Paragraph Text Card Title field in *AboutSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.paragraph_text_card_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_text_card_title: prismic.TitleField;

  /**
   * Paragraph Text Card Subtitle field in *AboutSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.paragraph_text_card_subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_text_card_subtitle: prismic.RichTextField;
}

/**
 * Primary content in *AboutSection → Items*
 */
export interface AboutSectionSliceDefaultItem {
  /**
   * Image field in *AboutSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *AboutSection → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *AboutSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  Simplify<AboutSectionSliceDefaultItem>
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Primary content in *HeaderSection → Primary*
 */
export interface HeaderSectionSliceDefaultPrimary {
  /**
   * Company Name field in *HeaderSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.company_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Sub_title field in *HeaderSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Button Text 1 field in *HeaderSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.button_text_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_1: prismic.KeyTextField;

  /**
   * Button Link 1 field in *HeaderSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.button_link_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_1: prismic.LinkField;

  /**
   * Button Text 2 field in *HeaderSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.button_text_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_2: prismic.KeyTextField;

  /**
   * Button Link 2 field in *HeaderSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.button_link_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_2: prismic.LinkField;

  /**
   * Image 1 field in *HeaderSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *HeaderSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *HeaderSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Text Card Title field in *HeaderSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.text_card_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_card_title: prismic.TitleField;

  /**
   * Text Card Subtitle field in *HeaderSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.primary.text_card_subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_card_subtitle: prismic.RichTextField;
}

/**
 * Primary content in *HeaderSection → Items*
 */
export interface HeaderSectionSliceDefaultItem {
  /**
   * Topics field in *HeaderSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_section.items[].topics
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  topics: prismic.KeyTextField;
}

/**
 * Default variation for HeaderSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSectionSliceDefaultPrimary>,
  Simplify<HeaderSectionSliceDefaultItem>
>;

/**
 * Slice variation for *HeaderSection*
 */
type HeaderSectionSliceVariation = HeaderSectionSliceDefault;

/**
 * HeaderSection Shared Slice
 *
 * - **API ID**: `header_section`
 * - **Description**: HeaderSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSectionSlice = prismic.SharedSlice<
  "header_section",
  HeaderSectionSliceVariation
>;

/**
 * Primary content in *TestimonialSection → Primary*
 */
export interface TestimonialSectionSliceDefaultPrimary {
  /**
   * Text Card Title field in *TestimonialSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.primary.text_card_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_card_title: prismic.TitleField;

  /**
   * Text Card Subtitle field in *TestimonialSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.primary.text_card_subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_card_subtitle: prismic.RichTextField;
}

/**
 * Primary content in *TestimonialSection → Items*
 */
export interface TestimonialSectionSliceDefaultItem {
  /**
   * Image field in *TestimonialSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *TestimonialSection → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *TestimonialSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Score field in *TestimonialSection → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].score
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  score: prismic.NumberField;
}

/**
 * Default variation for TestimonialSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSectionSliceDefaultPrimary>,
  Simplify<TestimonialSectionSliceDefaultItem>
>;

/**
 * Slice variation for *TestimonialSection*
 */
type TestimonialSectionSliceVariation = TestimonialSectionSliceDefault;

/**
 * TestimonialSection Shared Slice
 *
 * - **API ID**: `testimonial_section`
 * - **Description**: TestimonialSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSectionSlice = prismic.SharedSlice<
  "testimonial_section",
  TestimonialSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FloatwppDocument,
      FloatwppDocumentData,
      FloatwppDocumentDataWhatsappItem,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataNavigationItem,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceDefaultItem,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      HeaderSectionSlice,
      HeaderSectionSliceDefaultPrimary,
      HeaderSectionSliceDefaultItem,
      HeaderSectionSliceVariation,
      HeaderSectionSliceDefault,
      TestimonialSectionSlice,
      TestimonialSectionSliceDefaultPrimary,
      TestimonialSectionSliceDefaultItem,
      TestimonialSectionSliceVariation,
      TestimonialSectionSliceDefault,
    };
  }
}
