// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *home → Navigation*
 */
export interface HomeDocumentDataNavigationItem {
  /**
   * Label field in *home → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *home → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Adicione o seu link
   * - **API ID Path**: home.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

type HomeDocumentDataSlicesSlice =
  | CtaFooterSlice
  | HeroSlice
  | TestimonialsSlice;

type HomeDocumentDataSlices1Slice = TestimonialsSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * tslogo field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.tslogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  tslogo: prismic.ImageField<never>;

  /**
   * Name field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Adicione o Nome de sua Empresa
   * - **API ID Path**: home.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * Site Title field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Adicione o Título do seu Hero
   * - **API ID Path**: home.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  site_title: prismic.RichTextField;

  /**
   * Navigation field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<HomeDocumentDataNavigationItem>>;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices1[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices1: prismic.SliceZone<HomeDocumentDataSlices1Slice>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Testimonials documents
 */
interface TestimonialsDocumentData {
  /**
   * Quote field in *Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Avatar field in *Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Name field in *Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Enterprise Name field in *Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.enterprise_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  enterprise_name: prismic.KeyTextField;
}

/**
 * Testimonials document from Prismic
 *
 * - **API ID**: `testimonials`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialsDocumentData>,
    "testimonials",
    Lang
  >;

/**
 * Content for Topic documents
 */
interface TopicDocumentData {
  /**
   * Title field in *Topic*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: topic.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Topic*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: topic.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Topic document from Prismic
 *
 * - **API ID**: `topic`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TopicDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TopicDocumentData>, "topic", Lang>;

/**
 * Item in *topicos → textos*
 */
export interface TopicosDocumentDataTextosItem {
  /**
   * textos field in *topicos → textos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: topicos.textos[].textos
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  textos: prismic.KeyTextField;
}

/**
 * Content for topicos documents
 */
interface TopicosDocumentData {
  /**
   * textos field in *topicos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: topicos.textos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  textos: prismic.GroupField<Simplify<TopicosDocumentDataTextosItem>>;
}

/**
 * topicos document from Prismic
 *
 * - **API ID**: `topicos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TopicosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TopicosDocumentData>,
    "topicos",
    Lang
  >;

export type AllDocumentTypes =
  | HomeDocument
  | TestimonialsDocument
  | TopicDocument
  | TopicosDocument;

/**
 * Item in *CtaFooter → Default → Primary → socials*
 */
export interface CtaFooterSliceDefaultPrimarySocialsItem {
  /**
   * image field in *CtaFooter → Default → Primary → socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.socials[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * socials link field in *CtaFooter → Default → Primary → socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.socials[].socials_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  socials_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *CtaFooter → Default → Primary*
 */
export interface CtaFooterSliceDefaultPrimary {
  /**
   * title field in *CtaFooter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * sub field in *CtaFooter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.sub
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub: prismic.RichTextField;

  /**
   * button field in *CtaFooter → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  button: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * socials field in *CtaFooter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_footer.default.primary.socials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socials: prismic.GroupField<
    Simplify<CtaFooterSliceDefaultPrimarySocialsItem>
  >;
}

/**
 * Default variation for CtaFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaFooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaFooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaFooter*
 */
type CtaFooterSliceVariation = CtaFooterSliceDefault;

/**
 * CtaFooter Shared Slice
 *
 * - **API ID**: `cta_footer`
 * - **Description**: CtaFooter
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaFooterSlice = prismic.SharedSlice<
  "cta_footer",
  CtaFooterSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Topicos Hero*
 */
export interface HeroSliceDefaultPrimaryTopicosHeroItem {
  /**
   * Texto field in *Hero → Default → Primary → Topicos Hero*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.topicos_hero[].texto
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texto: prismic.RichTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Nome da Empresa field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Adicione o nome da empresa
   * - **API ID Path**: hero.default.primary.nome_da_empresa
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  nome_da_empresa: prismic.RichTextField;

  /**
   * Hero Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Adicione o Título do seu Hero
   * - **API ID Path**: hero.default.primary.hero_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_text: prismic.RichTextField;

  /**
   * Topicos Hero field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.topicos_hero[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  topicos_hero: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryTopicosHeroItem>
  >;

  /**
   * Button Contate field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Botão para contato
   * - **API ID Path**: hero.default.primary.button_contate
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_contate: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button SaibaMais field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_saibamais
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_saibamais: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Testimonials → Default → Primary → testimonial*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialItem {
  /**
   * Testimonial text field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].testimonial_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial_text: prismic.RichTextField;

  /**
   * Testimonial img field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].testimonial_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  testimonial_img: prismic.ImageField<never>;

  /**
   * testimonial user field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].testimonial_user
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial_user: prismic.RichTextField;

  /**
   * testimonial empresa field in *Testimonials → Default → Primary → testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].testimonial_empresa
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial_empresa: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Testimonials Titulo field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials_titulo
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonials_titulo: prismic.RichTextField;

  /**
   * Testimonials Subtitulo field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials_subtitulo
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonials_subtitulo: prismic.RichTextField;

  /**
   * Testimonials CTA field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials_cta
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonials_cta: prismic.RichTextField;

  /**
   * testimonial field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonial: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataNavigationItem,
      HomeDocumentDataSlicesSlice,
      HomeDocumentDataSlices1Slice,
      TestimonialsDocument,
      TestimonialsDocumentData,
      TopicDocument,
      TopicDocumentData,
      TopicosDocument,
      TopicosDocumentData,
      TopicosDocumentDataTextosItem,
      AllDocumentTypes,
      CtaFooterSlice,
      CtaFooterSliceDefaultPrimarySocialsItem,
      CtaFooterSliceDefaultPrimary,
      CtaFooterSliceVariation,
      CtaFooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryTopicosHeroItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
